# Generated by Django 4.2.6 on 2024-02-05 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exterior_calculate.utils_upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('straight', models.IntegerField(blank=True, null=True)),
                ('topology_cyclical', models.IntegerField(blank=True, null=True)),
                ('topology_chaotic', models.IntegerField(blank=True, null=True)),
                ('deformation', models.IntegerField(blank=True, null=True)),
                ('symmetry', models.IntegerField(blank=True, null=True)),
                ('curves', models.IntegerField(blank=True, null=True)),
                ('copy', models.IntegerField(blank=True, null=True)),
                ('mesh_optimization', models.IntegerField(blank=True, null=True)),
                ('ui_scan', models.IntegerField(blank=True, null=True)),
                ('creating_lod_forms', models.IntegerField(blank=True, null=True)),
                ('backing_lod', models.IntegerField(blank=True, null=True)),
                ('import_background_image', models.IntegerField(blank=True, null=True)),
                ('studying_information', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Additional Structure',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('low_poly', models.BooleanField(default=False)),
                ('high_poly', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('objects_type', models.CharField(choices=[('BuildDetails', 'BuildDetails'), ('Floor', 'Floor'), ('Objects', 'Objects')], max_length=30)),
                ('geometry_straight', models.CharField(blank=True, max_length=30, null=True)),
                ('geometry_curve', models.CharField(blank=True, max_length=30, null=True)),
                ('primitive', models.BooleanField(default=False)),
                ('deformation', models.CharField(blank=True, max_length=30, null=True)),
                ('symmetric', models.BooleanField(default=False)),
                ('copy', models.CharField(blank=True, max_length=30, null=True)),
                ('furniture', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('low_poly', models.BooleanField(default=False)),
                ('high_poly', models.BooleanField(default=False)),
                ('topology_cyclic', models.CharField(blank=True, max_length=30, null=True)),
                ('topology_chaotic', models.CharField(blank=True, max_length=30, null=True)),
                ('create_data', models.DateTimeField(auto_now_add=True)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='exterior_calculate.building')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to=exterior_calculate.utils_upload.screenshots)),
            ],
        ),
        migrations.CreateModel(
            name='TopologyHard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('topology_cyclic', models.CharField(blank=True, max_length=30, null=True)),
                ('topology_chaotic', models.CharField(blank=True, max_length=30, null=True)),
                ('geometry_straight', models.CharField(blank=True, max_length=30, null=True)),
                ('geometry_curve', models.CharField(blank=True, max_length=30, null=True)),
                ('primitive', models.BooleanField(default=False)),
                ('deformation', models.CharField(blank=True, max_length=30, null=True)),
                ('symmetric', models.BooleanField(default=False)),
                ('copy', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('low_poly', models.BooleanField(default=False)),
                ('high_poly', models.BooleanField(default=False)),
                ('screenshot_topology_hard', models.ManyToManyField(blank=True, to='exterior_calculate.projectsimage')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectExterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('Stab', 'Stab'), ('OffPlan', 'OffPlan'), ('tower', 'tower')], default='Stab', max_length=20)),
                ('project_name', models.CharField(max_length=255)),
                ('link_clickup', models.TextField(blank=True, null=True)),
                ('link_cet3', models.TextField(blank=True, null=True)),
                ('project_teg', models.CharField(choices=[('None', 'None'), ('Priority', 'Priority'), ('High priority', 'High priority')], default='None', max_length=20)),
                ('exterior_status', models.CharField(choices=[('open', 'open'), ('in progress', 'in progress'), ('complete', 'complete'), ('checked', 'checked'), ('correcting', 'correcting'), ('waiting', 'waiting')], default='open', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('texture', models.FileField(blank=True, null=True, upload_to=exterior_calculate.utils_upload.project_texture, validators=[exterior_calculate.utils_upload.validate_file_extension])),
                ('finished_point_low', models.CharField(blank=True, max_length=255, null=True)),
                ('finished_point_high', models.CharField(blank=True, max_length=255, null=True)),
                ('finished_time_low', models.CharField(blank=True, max_length=255, null=True)),
                ('finished_time_high', models.CharField(blank=True, max_length=255, null=True)),
                ('create_data', models.DateTimeField(auto_now_add=True)),
                ('project_ex_employee_user', models.ForeignKey(blank=True, limit_choices_to={'role': 'ExEmployee'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ex_employee_projects', to=settings.AUTH_USER_MODEL, verbose_name='EX Employee')),
                ('project_ex_teamlead_user', models.ForeignKey(blank=True, limit_choices_to={'role': 'ExTeamlead'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ex_teamlead_projects', to=settings.AUTH_USER_MODEL, verbose_name='EX Тимлид')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exterior_projects', to='project.region')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('geometry_straight', models.CharField(blank=True, max_length=30, null=True)),
                ('geometry_curve', models.CharField(blank=True, max_length=30, null=True)),
                ('primitive', models.BooleanField(default=False)),
                ('deformation', models.CharField(blank=True, max_length=30, null=True)),
                ('symmetric', models.BooleanField(default=False)),
                ('copy', models.CharField(blank=True, max_length=30, null=True)),
                ('furniture', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('low_poly', models.BooleanField(default=False)),
                ('high_poly', models.BooleanField(default=False)),
                ('topology_cyclic', models.CharField(blank=True, max_length=30, null=True)),
                ('topology_chaotic', models.CharField(blank=True, max_length=30, null=True)),
                ('create_data', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects_detail', to='exterior_calculate.buildingobjects')),
                ('screenshot_details', models.ManyToManyField(blank=True, to='exterior_calculate.projectsimage')),
                ('topology_hard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topology_hard', to='exterior_calculate.topologyhard')),
            ],
        ),
        migrations.AddField(
            model_name='buildingobjects',
            name='screenshot_objects',
            field=models.ManyToManyField(blank=True, to='exterior_calculate.projectsimage'),
        ),
        migrations.AddField(
            model_name='buildingobjects',
            name='topology_hard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topology_hard_objects', to='exterior_calculate.topologyhard'),
        ),
        migrations.AddField(
            model_name='building',
            name='project_exterior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='exterior_calculate.projectexterior'),
        ),
        migrations.AddField(
            model_name='building',
            name='screenshot_building',
            field=models.ManyToManyField(blank=True, to='exterior_calculate.projectsimage'),
        ),
    ]
