# Generated by Django 4.2.6 on 2024-02-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exterior_calculate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingobjects',
            name='topology_hard',
        ),
        migrations.RemoveField(
            model_name='objectsdetails',
            name='topology_hard',
        ),
        migrations.AddField(
            model_name='buildingobjects',
            name='topology_hard',
            field=models.ManyToManyField(blank=True, to='exterior_calculate.topologyhard'),
        ),
        migrations.AddField(
            model_name='objectsdetails',
            name='topology_hard',
            field=models.ManyToManyField(blank=True, to='exterior_calculate.topologyhard'),
        ),
    ]
