# Generated by Django 4.2.6 on 2024-02-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exterior_calculate', '0002_remove_buildingobjects_topology_hard_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalstructure',
            old_name='deformation',
            new_name='deformation_easy',
        ),
        migrations.AddField(
            model_name='additionalstructure',
            name='deformation_hard',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
