# Generated by Django 4.2.6 on 2024-02-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exterior_calculate', '0003_rename_deformation_additionalstructure_deformation_easy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingobjects',
            name='deformation_hard',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='objectsdetails',
            name='deformation_hard',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='topologyhard',
            name='deformation_hard',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
