# Generated by Django 4.2.6 on 2024-02-10 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exterior_calculate', '0004_buildingobjects_deformation_hard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='high_poly',
        ),
        migrations.RemoveField(
            model_name='buildingobjects',
            name='high_poly',
        ),
        migrations.RemoveField(
            model_name='buildingobjects',
            name='low_poly',
        ),
        migrations.RemoveField(
            model_name='objectsdetails',
            name='high_poly',
        ),
        migrations.RemoveField(
            model_name='objectsdetails',
            name='low_poly',
        ),
        migrations.RemoveField(
            model_name='topologyhard',
            name='high_poly',
        ),
        migrations.RemoveField(
            model_name='topologyhard',
            name='low_poly',
        ),
        migrations.RemoveField(
            model_name='topologyhard',
            name='topology_chaotic',
        ),
        migrations.RemoveField(
            model_name='topologyhard',
            name='topology_cyclic',
        ),
    ]
