# Generated by Django 4.2.6 on 2024-02-10 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exterior_calculate', '0005_remove_building_high_poly_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalstructure',
            old_name='backing_lod',
            new_name='high_poly',
        ),
        migrations.RenameField(
            model_name='additionalstructure',
            old_name='creating_lod_forms',
            new_name='low_poly',
        ),
        migrations.RemoveField(
            model_name='additionalstructure',
            name='import_background_image',
        ),
        migrations.RemoveField(
            model_name='additionalstructure',
            name='mesh_optimization',
        ),
        migrations.RemoveField(
            model_name='additionalstructure',
            name='studying_information',
        ),
        migrations.RemoveField(
            model_name='additionalstructure',
            name='ui_scan',
        ),
    ]
