# Generated by Django 4.2.6 on 2024-02-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exterior_calculate', '0007_alter_buildingobjects_building_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingobjects',
            name='copy',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='buildingobjects',
            name='deformation',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='buildingobjects',
            name='deformation_hard',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='buildingobjects',
            name='furniture',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='buildingobjects',
            name='geometry_curve',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='buildingobjects',
            name='geometry_straight',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='buildingobjects',
            name='topology_chaotic',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='buildingobjects',
            name='topology_cyclic',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='objectsdetails',
            name='copy',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='objectsdetails',
            name='deformation',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='objectsdetails',
            name='deformation_hard',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='objectsdetails',
            name='furniture',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='objectsdetails',
            name='geometry_curve',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='objectsdetails',
            name='geometry_straight',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='objectsdetails',
            name='topology_chaotic',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='objectsdetails',
            name='topology_cyclic',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='topologyhard',
            name='copy',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='topologyhard',
            name='deformation',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='topologyhard',
            name='deformation_hard',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='topologyhard',
            name='geometry_curve',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='topologyhard',
            name='geometry_straight',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
    ]
