# Generated by Django 4.2.6 on 2024-02-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exterior_calculate', '0008_alter_buildingobjects_copy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalstructure',
            name='low_poly',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
