# Generated by Django 4.2.6 on 2024-03-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exterior_calculate', '0010_alter_additionalstructure_high_poly'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='midl_poly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectexterior',
            name='finished_point_midl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectexterior',
            name='finished_time_midl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buildingobjects',
            name='primitive',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='objectsdetails',
            name='primitive',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
    ]
