# Generated by Django 4.2.6 on 2024-03-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exterior_calculate', '0011_building_midl_poly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexterior',
            name='in_stock_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectexterior',
            name='quantity_correcting',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectexterior',
            name='serial_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectexterior',
            name='stock_active',
            field=models.BooleanField(default=False),
        ),
    ]
