# Generated by Django 4.2.6 on 2024-03-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exterior_calculate', '0012_projectexterior_in_stock_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='finished_point',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='finished_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
