# Generated by Django 4.2.6 on 2024-04-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exterior_calculate', '0014_additionalstructure_arb_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='copy',
            field=models.IntegerField(default=0),
        ),
    ]
