# Generated by Django 4.2.6 on 2024-04-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exterior_calculate', '0015_building_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalstructure',
            name='arb_logo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additionalstructure',
            name='furniture',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additionalstructure',
            name='high_poly',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additionalstructure',
            name='logo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additionalstructure',
            name='low_poly',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additionalstructure',
            name='railing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additionalstructure',
            name='staircase_curves',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additionalstructure',
            name='staircase_straight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildingobjects',
            name='objects_type',
            field=models.CharField(choices=[('BuildDetails', 'BuildDetails'), ('Floor', 'Floor'), ('Objects', 'Objects'), ('StaticObject', 'StaticObject')], max_length=30),
        ),
    ]
