# Generated by Django 4.2.6 on 2024-04-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exterior_calculate', '0016_alter_additionalstructure_arb_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalstructure',
            name='high_poly',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
