# Generated by Django 4.2.6 on 2024-04-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exterior_calculate', '0017_alter_additionalstructure_high_poly'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalstructure',
            name='primitive',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
