# Generated by Django 4.2.6 on 2024-04-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exterior_calculate', '0018_additionalstructure_primitive'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexterior',
            name='calculated',
            field=models.BooleanField(default=False),
        ),
    ]
