# Generated by Django 4.2.6 on 2024-08-01 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exterior_calculate', '0020_exteriortask_exteriorstoragestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingobjects',
            name='primitive',
        ),
        migrations.RemoveField(
            model_name='topologyhard',
            name='primitive',
        ),
        migrations.AddField(
            model_name='buildingobjects',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='objectsdetails',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='topologyhard',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('create_data', models.DateTimeField(auto_now_add=True)),
                ('objects_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='exterior_calculate.buildingobjects')),
                ('screenshot_details', models.ManyToManyField(blank=True, to='exterior_calculate.projectsimage')),
                ('topology_hard', models.ManyToManyField(blank=True, to='exterior_calculate.topologyhard')),
            ],
        ),
    ]
