# Generated by Django 4.2.6 on 2024-08-04 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exterior_calculate', '0021_remove_buildingobjects_primitive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('geometry_straight', models.CharField(blank=True, default='0', max_length=30, null=True)),
                ('geometry_curve', models.CharField(blank=True, default='0', max_length=30, null=True)),
                ('primitive', models.CharField(blank=True, default='0', max_length=30, null=True)),
                ('deformation', models.CharField(blank=True, default='0', max_length=30, null=True)),
                ('deformation_hard', models.CharField(blank=True, default='0', max_length=30, null=True)),
                ('symmetric', models.BooleanField(default=False)),
                ('copy_count', models.CharField(blank=True, default='0', max_length=30, null=True)),
                ('furniture', models.CharField(blank=True, default='0', max_length=30, null=True)),
                ('logo', models.CharField(blank=True, default='0', max_length=30, null=True)),
                ('arb_logo', models.CharField(blank=True, default='0', max_length=30, null=True)),
                ('staircase_straight', models.CharField(blank=True, default='0', max_length=30, null=True)),
                ('staircase_curves', models.CharField(blank=True, default='0', max_length=30, null=True)),
                ('railing', models.CharField(blank=True, default='0', max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('topology_cyclic', models.CharField(blank=True, default='0', max_length=30, null=True)),
                ('topology_chaotic', models.CharField(blank=True, default='0', max_length=30, null=True)),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='building',
            old_name='copy',
            new_name='copy_count',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='create_data',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='low_poly',
            new_name='mid_poly',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='screenshot_building',
            new_name='screenshots',
        ),
        migrations.RenameField(
            model_name='buildingobjects',
            old_name='building_id',
            new_name='building',
        ),
        migrations.RenameField(
            model_name='buildingobjects',
            old_name='copy',
            new_name='copy_count',
        ),
        migrations.RenameField(
            model_name='buildingobjects',
            old_name='create_data',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='buildingobjects',
            old_name='screenshot_objects',
            new_name='screenshots',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='objects_detail_id',
            new_name='building_object',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='create_data',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='screenshot_details',
            new_name='screenshots',
        ),
        migrations.RenameField(
            model_name='topologyhard',
            old_name='copy',
            new_name='copy_count',
        ),
        migrations.RenameField(
            model_name='topologyhard',
            old_name='screenshot_topology_hard',
            new_name='screenshots',
        ),
        migrations.RemoveField(
            model_name='building',
            name='midl_poly',
        ),
        migrations.DeleteModel(
            name='ObjectsDetails',
        ),
        migrations.AddField(
            model_name='floors',
            name='building_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='exterior_calculate.buildingobjects'),
        ),
        migrations.AddField(
            model_name='floors',
            name='screenshots',
            field=models.ManyToManyField(blank=True, to='exterior_calculate.projectsimage'),
        ),
        migrations.AddField(
            model_name='floors',
            name='topology_hard',
            field=models.ManyToManyField(blank=True, to='exterior_calculate.topologyhard'),
        ),
    ]
