# Generated by Django 4.2.6 on 2024-08-20 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exterior_calculate', '0023_remove_buildingobjects_arb_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='building_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='exterior_calculate.floors'),
        ),
    ]
