# Generated by Django 4.2.6 on 2024-08-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exterior_calculate', '0024_alter_details_building_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='building_object',
            new_name='floors',
        ),
    ]
