# Generated by Django 4.2.6 on 2024-11-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exterior_calculate', '0026_details_objects_type_floors_objects_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalstructure',
            old_name='arb_logo',
            new_name='arabian_logo',
        ),
        migrations.RenameField(
            model_name='additionalstructure',
            old_name='curves',
            new_name='cyclic_copy',
        ),
        migrations.RenameField(
            model_name='additionalstructure',
            old_name='straight',
            new_name='geometry_curve',
        ),
        migrations.AddField(
            model_name='additionalstructure',
            name='geometry_straight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='additionalstructure',
            name='railing_curve',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
