# Generated by Django 4.2.6 on 2024-11-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exterior_calculate', '0028_additionalstructure_study_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalstructure',
            name='study_info',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
