# Generated by Django 4.2.6 on 2024-05-16 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import render.upload_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'open'), ('in_progress', 'in_progress'), ('complete', 'complete'), ('checked', 'checked'), ('correcting', 'correcting'), ('waiting', 'waiting')], default='open', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('sorted', models.BooleanField()),
                ('time_in_progress', models.DateTimeField(blank=True, null=True)),
                ('time_checked', models.DateTimeField(blank=True, null=True)),
                ('time_complete', models.DateTimeField(blank=True, null=True)),
                ('time_correcting', models.DateTimeField(blank=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_employee', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='RenderTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('render', 'render'), ('floor_plan', 'floor_plan')], max_length=20)),
                ('image_before', models.ImageField(upload_to=render.upload_utils.render_image)),
                ('image_after', models.ImageField(blank=True, null=True, upload_to=render.upload_utils.render_image)),
                ('status', models.CharField(choices=[('open', 'open'), ('in_progress', 'in_progress'), ('complete', 'complete'), ('checked', 'checked'), ('correcting', 'correcting'), ('waiting', 'waiting')], default='open', max_length=20)),
                ('new_task', models.BooleanField(default=True)),
                ('to_begin', models.BooleanField()),
                ('time_in_progress', models.DateTimeField(blank=True, null=True)),
                ('time_checked', models.DateTimeField(blank=True, null=True)),
                ('time_complete', models.DateTimeField(blank=True, null=True)),
                ('time_correcting', models.DateTimeField(blank=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_task', to='render.projectlisting')),
                ('task_employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_employee', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('task_qa_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_qa', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('asset', 'asset'), ('geometry', 'geometry'), ('render', 'render'), ('correcting_2d', 'correcting_2d')], default='asset', max_length=20)),
                ('status', models.CharField(choices=[('open', 'open'), ('in_progress', 'in_progress'), ('complete', 'complete'), ('checked', 'checked'), ('correcting', 'correcting'), ('waiting', 'waiting')], default='open', max_length=20)),
                ('time_in_progress', models.DateTimeField(blank=True, null=True)),
                ('time_checked', models.DateTimeField(blank=True, null=True)),
                ('time_complete', models.DateTimeField(blank=True, null=True)),
                ('time_correcting', models.DateTimeField(blank=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('sub_task_employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_task_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('sub_task_qa_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_task_qa', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('task_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_task', to='render.rendertask')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=render.upload_utils.project_file)),
                ('project_file_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_file', to='render.projectlisting')),
            ],
        ),
    ]
