# Generated by Django 4.2.6 on 2024-05-16 12:21

from django.db import migrations, models
import render.upload_utils


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(upload_to=render.upload_utils.project_file),
        ),
    ]
