# Generated by Django 4.2.6 on 2024-06-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0002_alter_projectfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendertask',
            name='image_after_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rendertask',
            name='image_before_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectlisting',
            name='sorted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rendertask',
            name='to_begin',
            field=models.BooleanField(default=False),
        ),
    ]
