# Generated by Django 4.2.6 on 2024-06-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0003_rendertask_image_after_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='file_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
