# Generated by Django 4.2.6 on 2024-06-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0004_projectfile_file_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlisting',
            name='sorted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='projectlisting',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('in_progress', 'in_progress'), ('complete', 'complete'), ('checked', 'checked'), ('correcting', 'correcting'), ('waiting', 'waiting')], db_index=True, default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectlisting',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rendertask',
            name='new_task',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='rendertask',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('in_progress', 'in_progress'), ('complete', 'complete'), ('checked', 'checked'), ('correcting', 'correcting'), ('waiting', 'waiting')], db_index=True, default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('in_progress', 'in_progress'), ('complete', 'complete'), ('checked', 'checked'), ('correcting', 'correcting'), ('waiting', 'waiting')], db_index=True, default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='type',
            field=models.CharField(choices=[('asset', 'asset'), ('geometry', 'geometry'), ('render', 'render'), ('correcting_2d', 'correcting_2d')], db_index=True, default='asset', max_length=20),
        ),
        migrations.AddIndex(
            model_name='projectlisting',
            index=models.Index(fields=['title'], name='render_proj_title_6ba1ad_idx'),
        ),
        migrations.AddIndex(
            model_name='projectlisting',
            index=models.Index(fields=['user_id'], name='render_proj_user_id_62de20_idx'),
        ),
        migrations.AddIndex(
            model_name='projectlisting',
            index=models.Index(fields=['employee_id'], name='render_proj_employe_8da5a8_idx'),
        ),
        migrations.AddIndex(
            model_name='projectlisting',
            index=models.Index(fields=['status'], name='render_proj_status_4a1623_idx'),
        ),
        migrations.AddIndex(
            model_name='projectlisting',
            index=models.Index(fields=['sorted'], name='render_proj_sorted_0acfdc_idx'),
        ),
        migrations.AddIndex(
            model_name='rendertask',
            index=models.Index(fields=['project_id'], name='render_rend_project_3d3dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='rendertask',
            index=models.Index(fields=['new_task'], name='render_rend_new_tas_ea41ca_idx'),
        ),
        migrations.AddIndex(
            model_name='rendertask',
            index=models.Index(fields=['status'], name='render_rend_status_ced0c8_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['task_id'], name='render_subt_task_id_ffc3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['type'], name='render_subt_type_018cd8_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['status'], name='render_subt_status_d4a7bb_idx'),
        ),
    ]
