# Generated by Django 4.2.6 on 2024-07-05 11:39

from django.db import migrations, models
import render.upload_utils


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0007_rendertask_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendertaskimages',
            name='floor_plan_image',
            field=models.ImageField(null=True, upload_to=render.upload_utils.floor_plan_render_image),
        ),
    ]
