# Generated by Django 4.2.6 on 2024-07-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0008_rendertaskimages_floor_plan_image'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rendertaskimages',
            name='render_rend_task_id_0f35f0_idx',
        ),
        migrations.RemoveField(
            model_name='rendertaskimages',
            name='task_id',
        ),
        migrations.AddField(
            model_name='rendertask',
            name='images',
            field=models.ManyToManyField(null=True, related_name='render_tasks', to='render.rendertaskimages'),
        ),
        migrations.AddIndex(
            model_name='rendertaskimages',
            index=models.Index(fields=['task_images_employee_id'], name='render_rend_task_im_59805c_idx'),
        ),
    ]
