# Generated by Django 4.2.6 on 2024-07-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0009_remove_rendertaskimages_render_rend_task_id_0f35f0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendertask',
            name='images',
            field=models.ManyToManyField(null=True, related_name='task_images', to='render.rendertaskimages'),
        ),
    ]
