# Generated by Django 4.2.6 on 2024-07-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0010_alter_rendertask_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendertask',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='task_images', to='render.rendertaskimages'),
        ),
    ]
