# Generated by Django 4.2.6 on 2024-07-09 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0012_rendertaskimages_checked_is_rendertaskimages_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendertaskimages',
            name='desc',
        ),
        migrations.CreateModel(
            name='MessageTaskImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('task_images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_images_message', to='render.rendertaskimages')),
            ],
        ),
    ]
