# Generated by Django 4.2.6 on 2024-07-09 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0013_remove_rendertaskimages_desc_messagetaskimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetaskimages',
            name='task_images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_images_messages', to='render.rendertaskimages'),
        ),
    ]
