# Generated by Django 4.2.6 on 2024-07-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0014_alter_messagetaskimages_task_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendertask',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='task_images', to='render.rendertaskimages'),
        ),
    ]
