# Generated by Django 4.2.6 on 2024-07-10 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('render', '0015_alter_rendertask_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetaskimages',
            name='user_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_message_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
