# Generated by Django 4.2.6 on 2024-07-11 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0017_messagerendertask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagerendertask',
            name='render_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='render_task_messages', to='render.rendertask'),
        ),
    ]
