# Generated by Django 4.2.6 on 2024-07-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0018_alter_messagerendertask_render_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendertaskimages',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('in_progress', 'in_progress'), ('complete', 'complete'), ('checked', 'checked'), ('correcting', 'correcting'), ('waiting', 'waiting')], db_index=True, default='open', max_length=20),
        ),
    ]
