# Generated by Django 4.2.6 on 2024-07-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0021_messagerendertask_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
