# Generated by Django 4.2.6 on 2024-07-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0022_subtask_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlisting',
            name='listing_amt',
            field=models.IntegerField(default=0),
        ),
    ]
