# Generated by Django 4.2.6 on 2024-07-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0023_projectlisting_listing_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlisting',
            name='time_listing_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
