# Generated by Django 4.2.6 on 2024-07-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0024_projectlisting_time_listing_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlisting',
            name='priority',
            field=models.CharField(choices=[('open', 'open'), ('in_progress', 'in_progress'), ('complete', 'complete'), ('checked', 'checked'), ('correcting', 'correcting'), ('waiting', 'waiting')], db_index=True, default='1', max_length=20),
        ),
    ]
