# Generated by Django 4.2.6 on 2024-07-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0025_projectlisting_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlisting',
            name='priority',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], db_index=True, default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectlisting',
            name='time_listing_update',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
