# Generated by Django 4.2.6 on 2024-07-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0026_alter_projectlisting_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendertask',
            name='image_after_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='projectlisting',
            index=models.Index(fields=['priority'], name='render_proj_priorit_6a8e7b_idx'),
        ),
    ]
