# Generated by Django 4.2.6 on 2024-08-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0027_rendertask_image_after_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlisting',
            name='priority_enhancer',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], db_index=True, default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectlisting',
            name='priority',
            field=models.CharField(choices=[('Low Priority', 'Low Priority'), ('Medium Priority', 'Medium Priority'), ('High Priority', 'High Priority')], db_index=True, default='Low Priority', max_length=20),
        ),
        migrations.AddIndex(
            model_name='projectlisting',
            index=models.Index(fields=['priority_enhancer'], name='render_proj_priorit_9c6547_idx'),
        ),
    ]
