# Generated by Django 4.2.6 on 2024-08-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0028_projectlisting_priority_enhancer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlisting',
            name='priority',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], db_index=True, default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectlisting',
            name='priority_enhancer',
            field=models.CharField(choices=[('Low Priority', 'Low Priority'), ('Medium Priority', 'Medium Priority'), ('High Priority', 'High Priority')], db_index=True, default='Low Priority', max_length=20),
        ),
    ]
