# Generated by Django 4.2.6 on 2024-08-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0029_alter_projectlisting_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlisting',
            name='priority_enhancer',
            field=models.CharField(choices=[('None', 'None'), ('Low Priority', 'Low Priority'), ('Medium Priority', 'Medium Priority'), ('High Priority', 'High Priority')], db_index=True, default='None', max_length=20),
        ),
    ]
