# Generated by Django 4.2.6 on 2024-08-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0030_alter_projectlisting_priority_enhancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlisting',
            name='floor_plan_check',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
