# Generated by Django 4.2.6 on 2024-08-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0031_projectlisting_floor_plan_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlisting',
            name='action_required',
            field=models.CharField(choices=[('None', 'None'), ('Waiting', 'Waiting'), ('Trash', 'Trash')], db_index=True, default='None', max_length=20),
        ),
        migrations.AddIndex(
            model_name='projectlisting',
            index=models.Index(fields=['action_required'], name='render_proj_action__0cfb69_idx'),
        ),
    ]
