# Generated by Django 4.2.6 on 2024-08-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0032_projectlisting_action_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlisting',
            name='is_delete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='projectlisting',
            index=models.Index(fields=['is_delete'], name='render_proj_is_dele_8d0ce5_idx'),
        ),
    ]
