# Generated by Django 4.2.6 on 2024-08-22 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('render', '0033_projectlisting_is_delete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageActiveUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('patch', 'patch'), ('delete', 'delete')], db_index=True, max_length=20)),
                ('table', models.CharField(db_index=True, max_length=256)),
                ('fields', models.TextField(db_index=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'action'], name='render_stor_user_id_0e66a7_idx'), models.Index(fields=['user', 'create_at'], name='render_stor_user_id_6c0b4f_idx'), models.Index(fields=['user'], name='render_stor_user_id_b0c2c7_idx'), models.Index(fields=['action'], name='render_stor_action_5889dc_idx'), models.Index(fields=['fields'], name='render_stor_fields_78f361_idx'), models.Index(fields=['create_at'], name='render_stor_create__47a915_idx')],
            },
        ),
    ]
