# Generated by Django 4.2.6 on 2024-08-28 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('render', '0034_storageactiveuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderTaskStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_task_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('old_status', models.CharField(choices=[('open', 'open'), ('in_progress', 'in_progress'), ('complete', 'complete'), ('checked', 'checked'), ('correcting', 'correcting'), ('waiting', 'waiting')], max_length=20)),
                ('new_status', models.CharField(choices=[('open', 'open'), ('in_progress', 'in_progress'), ('complete', 'complete'), ('checked', 'checked'), ('correcting', 'correcting'), ('waiting', 'waiting')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to='render.rendertask')),
            ],
            options={
                'indexes': [models.Index(fields=['task'], name='render_rend_task_id_dfc54f_idx'), models.Index(fields=['project_name'], name='render_rend_project_08ad35_idx'), models.Index(fields=['changed_at'], name='render_rend_changed_f066e8_idx')],
            },
        ),
    ]
