# Generated by Django 4.2.6 on 2024-08-30 10:49

from django.db import migrations, models
import render.upload_utils


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0036_projectlisting_time_render_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendertask',
            name='image_after_old',
            field=models.ImageField(blank=True, null=True, upload_to=render.upload_utils.render_image),
        ),
        migrations.AddField(
            model_name='rendertask',
            name='image_after_old_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
