# Generated by Django 4.2.6 on 2024-09-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0037_rendertask_image_after_old_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendertask',
            name='teg',
            field=models.CharField(choices=[('none', 'none'), ('main', 'main')], db_index=True, default='none', max_length=20),
        ),
    ]
