# Generated by Django 4.2.6 on 2024-12-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('None', 'None'), ('Low Priority', 'Priority'), ('Midl priority', 'Midl priority'), ('High priority', 'High priority')], db_index=True, default='None', max_length=20),
        ),
    ]
