# Generated by Django 4.2.6 on 2025-01-11 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interior', '0002_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='filter_teg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filters_teg', to='interior.projectsfilterteg'),
        ),
        migrations.CreateModel(
            name='PriorityTasksStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tasks', models.ManyToManyField(blank=True, related_name='priority_tasks', to='interior.task')),
                ('users', models.ManyToManyField(blank=True, related_name='user_priority_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи для выполнения задач')),
            ],
        ),
    ]
