# Generated by Django 4.2.6 on 2024-04-01 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.utils_upload


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0003_remove_task_copy_bedroom_remove_task_unique_bedroom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to=project.utils_upload.message_image)),
            ],
        ),
        migrations.CreateModel(
            name='TaskMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=1024, null=True)),
                ('create_data', models.DateTimeField(auto_now_add=True)),
                ('message_image', models.ManyToManyField(blank=True, to='project.messageimage')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TaskMessageTask', to='project.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TaskMessageUser', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
