# Generated by Django 4.2.6 on 2024-04-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_messageimage_taskmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type_group',
            field=models.CharField(choices=[('projects', 'projects'), ('no projects', 'no projects')], default='projects', max_length=20),
        ),
    ]
