# Generated by Django 4.2.6 on 2024-04-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_task_task_type_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, choices=[('with', 'with'), ('without', 'without'), ('gltf', 'gltf'), ('assemble', 'assemble'), ('upload', 'upload'), ('render2d', 'render2d'), ('render3d', 'render3d')], max_length=20, null=True),
        ),
    ]
