# Generated by Django 4.2.6 on 2024-04-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project_teg',
            field=models.CharField(choices=[('None', 'None'), ('Priority', 'Priority'), ('High priority', 'High priority')], default='None', max_length=20),
        ),
    ]
