# Generated by Django 4.2.6 on 2024-04-04 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_task_project_teg'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSONCalculateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_apartment', models.CharField(max_length=100)),
                ('assemble_plan', models.CharField(max_length=100)),
                ('copy', models.CharField(max_length=100)),
                ('upload_easy', models.CharField(max_length=100)),
                ('upload_medium', models.CharField(max_length=100)),
                ('upload_hard', models.CharField(max_length=100)),
                ('upload_texture', models.BooleanField(default=False)),
                ('pool', models.CharField(max_length=100)),
                ('grass', models.CharField(max_length=100)),
                ('asset', models.CharField(max_length=100)),
                ('json_data', models.JSONField()),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JSONCalculateData', to='project.task')),
            ],
        ),
    ]
