# Generated by Django 4.2.6 on 2024-04-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_jsoncalculatedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsoncalculatedata',
            name='json_data',
            field=models.TextField(),
        ),
    ]
