# Generated by Django 4.2.6 on 2024-04-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_jsoncalculatedata_json_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsoncalculatedata',
            name='json_data',
            field=models.JSONField(),
        ),
    ]
