# Generated by Django 4.2.6 on 2024-04-04 14:13

from django.db import migrations, models
import project.utils_upload


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_jsoncalculatedata_json_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsoncalculatedata',
            name='assemble_plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jsoncalculatedata',
            name='asset',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jsoncalculatedata',
            name='copy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jsoncalculatedata',
            name='grass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jsoncalculatedata',
            name='json_data',
            field=models.JSONField(default=project.utils_upload.save_default),
        ),
        migrations.AlterField(
            model_name='jsoncalculatedata',
            name='pool',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jsoncalculatedata',
            name='total_apartment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jsoncalculatedata',
            name='upload_easy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jsoncalculatedata',
            name='upload_hard',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jsoncalculatedata',
            name='upload_medium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
