# Generated by Django 4.2.6 on 2024-04-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_jsoncalculatedata_assemble_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsoncalculatedata',
            name='total_apartment',
            field=models.IntegerField(default=0),
        ),
    ]
