# Generated by Django 4.2.6 on 2024-04-08 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_jsoncalculatedata_total_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='task_render2d_upload',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_render2d_upload', to='project.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('none', 'none'), ('with', 'with'), ('without', 'without'), ('gltf', 'gltf'), ('assemble', 'assemble'), ('upload', 'upload'), ('render2d', 'render2d'), ('render2d_upload', 'render2d_upload'), ('render3d', 'render3d')], default='none', max_length=20),
        ),
    ]
