# Generated by Django 4.2.6 on 2024-04-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_alter_jsoncalculatedata_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsoncalculatedata',
            name='assemble_plan',
        ),
        migrations.RemoveField(
            model_name='jsoncalculatedata',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='jsoncalculatedata',
            name='copy',
        ),
        migrations.RemoveField(
            model_name='jsoncalculatedata',
            name='grass',
        ),
        migrations.RemoveField(
            model_name='jsoncalculatedata',
            name='pool',
        ),
        migrations.RemoveField(
            model_name='jsoncalculatedata',
            name='total_apartment',
        ),
        migrations.RemoveField(
            model_name='jsoncalculatedata',
            name='upload_easy',
        ),
        migrations.RemoveField(
            model_name='jsoncalculatedata',
            name='upload_hard',
        ),
        migrations.RemoveField(
            model_name='jsoncalculatedata',
            name='upload_medium',
        ),
        migrations.RemoveField(
            model_name='jsoncalculatedata',
            name='upload_texture',
        ),
    ]
