# Generated by Django 4.2.6 on 2024-04-08 13:53

from django.db import migrations, models
import project.utils_upload


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_remove_jsoncalculatedata_assemble_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='json_data',
            field=models.JSONField(default=project.utils_upload.save_default),
        ),
    ]
