# Generated by Django 4.2.6 on 2024-04-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_task_json_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JSONCalculateData',
        ),
    ]
