# Generated by Django 4.2.6 on 2024-04-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_delete_jsoncalculatedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='json_data',
        ),
        migrations.AddField(
            model_name='task',
            name='json_data_calculate',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
