# Generated by Django 4.2.6 on 2024-07-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_task_additional_time_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_task_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_teg',
            field=models.CharField(choices=[('None', 'None'), ('Priority', 'Priority'), ('High priority', 'High priority')], db_index=True, default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='stock_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('open', 'open'), ('in progress', 'in progress'), ('complete', 'complete'), ('checked', 'checked'), ('correcting', 'correcting'), ('waiting', 'waiting')], db_index=True, default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('none', 'none'), ('with', 'with'), ('without', 'without'), ('gltf', 'gltf'), ('assemble', 'assemble'), ('upload', 'upload'), ('render2d', 'render2d'), ('render2d_upload', 'render2d_upload'), ('render3d', 'render3d')], db_index=True, default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type_group',
            field=models.CharField(choices=[('projects', 'projects'), ('no projects', 'no projects')], db_index=True, default='projects', max_length=20),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_name'], name='project_pro_project_97e63e_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_teamlead_user'], name='project_pro_project_8d59ec_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['task_with'], name='project_pro_task_wi_47686f_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['task_without'], name='project_pro_task_wi_fbc182_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['task_assemble'], name='project_pro_task_as_19e271_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['task_gltf'], name='project_pro_task_gl_0f6fc0_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['task_upload'], name='project_pro_task_up_3dac77_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['task_render2d'], name='project_pro_task_re_110deb_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['task_render2d_upload'], name='project_pro_task_re_9d32d7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['task_render3d'], name='project_pro_task_re_c2be8a_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_employee_user'], name='project_tas_task_em_194e63_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['check_out_user'], name='project_tas_check_o_9085b7_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project_task_name'], name='project_tas_project_07f93f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_status'], name='project_tas_task_st_82050e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_type'], name='project_tas_task_ty_86c6d6_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_type_group'], name='project_tas_task_ty_74d744_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['stock_active'], name='project_tas_stock_a_b7f817_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project_teg'], name='project_tas_project_83aa6c_idx'),
        ),
    ]
