# Generated by Django 4.2.6 on 2024-05-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_myuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Teamlead', 'Teamlead'), ('Manager', 'Manager'), ('QA', 'QA'), ('Employee', 'Employee'), ('ExQA', 'ExQA'), ('ExTeamlead', 'ExTeamlead'), ('ExEmployee', 'ExEmployee'), ('ExAdmin', 'ExAdmin'), ('ExManager', 'ExManager'), ('Uploader', 'Uploader'), ('RenderQA', 'RenderQA')], default='Employee', max_length=20),
        ),
    ]
