# Generated by Django 4.2.6 on 2024-11-13 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_alter_teams_teamlead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='employees',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': ['Employee', 'InteriorEmployee']}, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teams',
            name='teamlead',
            field=models.OneToOneField(limit_choices_to={'role__in': ['Teamlead', 'InteriorTeamLead']}, on_delete=django.db.models.deletion.CASCADE, related_name='teamlead', to=settings.AUTH_USER_MODEL),
        ),
    ]
