# Generated by Django 4.2.6 on 2024-11-18 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_alter_teams_employees_alter_teams_teamlead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='telegram_id',
        ),
        migrations.AlterField(
            model_name='teams',
            name='employees',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['Employee', 'InteriorEmployee']}, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
